/* Generated By:JavaCC: Do not edit this line. EscanerConstants.java */
package org.grupo21.Escaner;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface EscanerConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int ADD = 5;
	/** RegularExpression Id. */
	int SUB = 6;
	/** RegularExpression Id. */
	int MUL = 7;
	/** RegularExpression Id. */
	int DIV = 8;
	/** RegularExpression Id. */
	int IGU = 9;
	/** RegularExpression Id. */
	int LBR = 10;
	/** RegularExpression Id. */
	int RBR = 11;
	/** RegularExpression Id. */
	int INT = 12;
	/** RegularExpression Id. */
	int INVERSION = 13;
	/** RegularExpression Id. */
	int INGRESOSCONT = 14;
	/** RegularExpression Id. */
	int INGRESOSDISCONT = 15;
	/** RegularExpression Id. */
	int DIVIDENDOS = 16;
	/** RegularExpression Id. */
	int DEUDA = 17;
	/** RegularExpression Id. */
	int MARGENVENTA = 18;
	/** RegularExpression Id. */
	int ROA = 19;
	/** RegularExpression Id. */
	int TIR = 20;
	/** RegularExpression Id. */
	int RECUPEROINV = 21;
	/** RegularExpression Id. */
	int CAPITAL = 22;
	/** RegularExpression Id. */
	int INDICADOR = 23;
	/** RegularExpression Id. */
	int LOWER = 24;
	/** RegularExpression Id. */
	int GREATER = 25;
	/** RegularExpression Id. */
	int LOWEREQUAL = 26;
	/** RegularExpression Id. */
	int GREATEREQUAL = 27;
	/** RegularExpression Id. */
	int EQUAL = 28;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"+\"", "\"-\"", "\"*\"", "\"/\"",
			"\"=\"", "\"(\"", "\")\"", "<INT>", "\"inversion_inicial\"", "\"ingresos_continuos\"",
			"\"ingresos_discontinuos\"", "\"dividendos\"", "\"deuda\"", "\"margen_venta\"", "\"roa\"", "\"tir\"",
			"\"recupero_inversion\"", "\"capital_total\"", "<INDICADOR>", "\"<\"", "\">\"", "\"<=\"", "\">=\"",
			"\"==\"", };

}
